<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Aspire\ServiceDefaults\ServiceDefaults.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\..\Services\Catalog\Models\Product.cs">
        <Link>Models\Product.cs</Link>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ApiClients\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="13.4.2" />
    </ItemGroup>

</Project>
