@Catalog_HostAddress = https://localhost:7234/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/1
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
    "id": 10,
    "name": "NEW Swn Flashlight",
    "description": "A NEW swn product for outdoor enthusiasts",
    "price": 59.99,
    "imageUrl": "product10.png"
}

###

PUT {{Catalog_HostAddress}}/10
Content-Type: application/json
{    
    "name": "UPDATED Swn Flashlight",
    "description": "An UPDATED swn product for outdoor enthusiasts",
    "price": 19.99,
    "imageUrl": "product10.png"
}

### update price

PUT {{Catalog_HostAddress}}/1
Content-Type: application/json
{    
    "name": "Solar Powered Flashlight",
    "description": "A fantastic product for outdoor enthusiasts",
    "price": 5.99,
    "imageUrl": "product1.png"
}

###

DELETE {{Catalog_HostAddress}}/10
Content-Type: application/json

### Support AI

GET {{Catalog_HostAddress}}/support/give-me-1-outdoor-activity
Accept: application/json

### Traditional Search

GET {{Catalog_HostAddress}}/search/Hiking
Accept: application/json

### AI Search

GET {{Catalog_HostAddress}}/aisearch/Something_for_rainy_days
Accept: application/json

###