name: Merge to main

on:
  push:
    branches-ignore:
      - main # This prevents the workflow from running on pushes to main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # This checks out the source branch of the push

      - name: Set up Git
        run: |
          git config --global user.email "subhasishbiswas15@gmail.com"
          git config --global user.name "SUBHASISHBISWAS"

      - name: Merge branch to main
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff --allow-unrelated-histories "${{ github.ref }}" # Corrected to use github.ref and allow unrelated histories
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the provided GITHUB_TOKEN
